my_dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: <account_identifier>
      user: <your_username>
      password: <your_password>
      role: <your_role>
      database: <your_database>
      warehouse: <your_warehouse>
      schema: <your_schema>
      threads: 4
      client_session_keep_alive: False
